AWSTemplateFormatVersion: '2010-09-09'

Resources:

  DartRankingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dart-ranking-cfn-dev

      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: playerId
          AttributeType: S

      KeySchema:
        - AttributeName: playerId
          KeyType: HASH

  DartAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: darts-app-cfn-dev-bucket

  DartAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DartAppBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${DartAppBucket}/*"
            Condition: 
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DartAppCloudFront}"

  DartLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dart-lambda-role-cfn-dev

      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                Resource: !GetAtt DartRankingTable.Arn

  DartLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: dart-lambda-cfn-dev
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt DartLambdaRole.Arn

      Code:
        S3Bucket: !Ref DartAppBucket
        S3Key: lambda/saveDartScore.zip

      Environment:
        Variables:
          TABLE_NAME: !Ref DartRankingTable

  DartLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt DartLambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DartHttpApi}/*/*/*"

  DartHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: dart-api-cfn-dev
      ProtocolType: HTTP

  DartHttpApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref DartHttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt DartLambda.Arn
      PayloadFormatVersion: "2.0"

  DartHttpApiRouteDelete:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DartHttpApi
      RouteKey: DELETE /delete
      Target: !Join
        - /
        - - integrations
          - !Ref DartHttpApiIntegration

  DartHttpApiRouteRanking:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DartHttpApi
      RouteKey: GET /ranking
      Target: !Join
        - /
        - - integrations
          - !Ref DartHttpApiIntegration

  DartHttpApiRouteSave:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DartHttpApi
      RouteKey: POST /save
      Target: !Join
        - /
        - - integrations
          - !Ref DartHttpApiIntegration

  DartHttpApiRouteScore:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DartHttpApi
      RouteKey: GET /score
      Target: !Join
        - /
        - - integrations
          - !Ref DartHttpApiIntegration

  DartHttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref DartHttpApi
      StageName: $default
      AutoDeploy: true

  DartAppCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: DartAppS3Origin
            DomainName: !GetAtt DartAppBucket.RegionalDomainName
            OriginAccessControlId: !Ref DartAppOriginAccessControl
            S3OriginConfig: {}

        DefaultCacheBehavior:
          TargetOriginId: DartAppS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods: 
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

        DefaultRootObject: index.html
        Enabled: true

  DartAppOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: DartAppOAC
        OriginAccessControlOriginType: s3
        SigningProtocol: sigv4
        SigningBehavior: always

Outputs:
  TableName:
    Value: !Ref DartRankingTable
