AWSTemplateFormatVersion: '2010-09-09'

Resources:

  DartRankingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dart-ranking-cfn-dev

      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: playerId
          AttributeType: S

      KeySchema:
        - AttributeName: playerId
          KeyType: HASH

  DartAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: darts-app-cfn-dev-bucket

  DartLambda:
    Type: AWS::Lambda::Function

Outputs:
  TableName:
    Value: !Ref DartRankingTable
